name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 0 1 * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env: 
        ddk: ${{secrets.DOCKER_DEPLOY_KEY}}
      run: echo $ddk | docker login -u flohsg --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dohtor:$(date +%s) -t dohtor:latest
    - name: docker push
      run: docker push dohtor
    - name: docker logout
      run: docker logout
